name: Release

on:
  push:

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: DataBurst Python Semantic Versioning
        uses: mostafaghadimi/python-semantic-versioning@main
        with:
          gh_token: ${{ secrets.GITHUB_TOKEN }}
          debug: true
